GCCFLAGS+= -march=native
GCCFLAGS+= -O2

CPPFLAGS+= -pedantic
CPPFLAGS+= -Wall
CPPFLAGS+= -Wcast-qual
CPPFLAGS+= -Wextra
CPPFLAGS+= -Wmissing-include-dirs
CPPFLAGS+= -Wold-style-cast
CPPFLAGS+= -Wredundant-decls
CPPFLAGS+= -Wshadow
CPPFLAGS+= -Wsign-conversion
CPPFLAGS+= -Wswitch-default
CPPFLAGS+= -Werror


all:
	g++ $(GCCFLAGS) $(CPPFLAGS) day?.cpp
